export const categories = [
    { id: 1, name: 'Business' },
    { id: 2, name: 'Marketing' },
    { id: 3, name: 'Technology' },
    { id: 4, name: 'Design' },
    { id: 5, name: 'Finance' },
    { id: 6, name: 'Health' },
    { id: 7, name: 'Education' },
    { id: 8, name: 'Travel' },
    { id: 9, name: 'Food' },
    { id: 10, name: 'Lifestyle' },
    { id: 11, name: 'Sports' },
    { id: 12, name: 'Entertainment' },
    { id: 13, name: 'News' },
    { id: 14, name: 'Science' },
    { id: 15, name: 'Art' },
    { id: 16, name: 'History' },
    { id: 17, name: 'Culture' },
    { id: 18, name: 'Politics' },
    { id: 19, name: 'Economics' },
    { id: 20, name: 'Environment' },
    { id: 21, name: 'Nature' },
    { id: 22, name: 'Music' },
    { id: 23, name: 'Movies' },
    { id: 24, name: 'Books' },
    { id: 25, name: 'Theater' },
    { id: 26, name: 'Fashion' },
    { id: 27, name: 'Photography' },
    { id: 28, name: 'DIY' },
    { id: 29, name: 'Gardening' },
    { id: 30, name: 'Crafts' },
    { id: 31, name: 'Parenting' },
    { id: 32, name: 'Relationships' },
    { id: 33, name: 'Self-Improvement' },
    { id: 34, name: 'Fitness' },
    { id: 35, name: 'Wellness' },
    { id: 36, name: 'Personal Finance' },
    { id: 37, name: 'Investing' },
    { id: 38, name: 'Real Estate' },
    { id: 39, name: 'Legal' },
    { id: 40, name: 'Automotive' },
  ];
  
  